"""SI table (section S13): two-dimensional potentials, MD against the functionals trained on planar profiles.
From salt_in_polymer_field2d/field2d_summary.json (figs/field2d_compare.py).  Writes si/si_tab_field2d.tex."""
import json, numpy as np
d = json.load(open("/mnt/research/MultiscaleML_group/Liyao/salt_in_polymer_field2d/field2d_summary.json"))
POT = {"p50": "egg carton", "p51": "neutral rods", "p52": "charged rods", "p53": "checkerboard"}
lines = []
for sysname, e in (("eps75", "7.5"), ("eps2", "2")):
    for i, tag in enumerate(("p50", "p51", "p52", "p53")):
        r = d[f"{sysname}/{tag}"]
        nf, pc, pb = r["neural functional"], r["pair closure"][0], r["Poisson-Boltzmann"][0]
        m = lambda k: np.mean([x[k] for x in nf])
        lines.append(f"{e if i == 0 else ''} & {POT[tag]} & {nf[0]['n_driven']:.0f} + {nf[0]['n_undriven']:.0f} & "
                     f"{m('pull'):.1f} & {m('amp_driven'):.1f} & {m('L2'):.1f} ({m('floor'):.1f}) & "
                     f"{pc['pull']:.1f} & {pc['amp_driven']:.1f} & {pb['pull']:.0f}\\\\")
tab = r"""\begin{table}[h]
\centering
\caption{Two-dimensional potentials at $c=0.04$: the functionals trained on planar profiles against MD. Significant Fourier modes of the density maps (driven + generated by the coupling of the driven ones), the root-mean-square deviation of their amplitudes in MD standard errors, the error of the driven amplitudes, and the band-limited error of the map with the MD noise level in parentheses. Neural functional: mean of three seeds.}
\label{tab:S:field2d}
\begin{tabular}{llccccccc}
 & & & \multicolumn{3}{c}{neural functional} & \multicolumn{2}{c}{pair closure} & PB\\
\cmidrule(lr){4-6}\cmidrule(lr){7-8}
$\varepsilon_r$ & potential & modes & rms dev. & driven (\%) & map (\%) & rms dev. & driven (\%) & rms dev.\\
\midrule
""" + "\n".join(lines) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
open("/mnt/gs21/scratch/lyuliyao/salt_in_polymer/paper/output/latex/si/si_tab_field2d.tex", "w").write(tab)
print(tab)
