#!/usr/bin/env python3

import argparse
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import model as M


RMIN = 0.25


def section(fh, name, sig, S, rc, npts):
    r = np.linspace(RMIN, rc, npts)
    u = -S * ((sig / r) ** 4 - (sig / rc) ** 4)
    f = -4.0 * S * sig ** 4 / r ** 5
    fh.write(f"# ion-monomer solvation, s={sig}, S={S}, rc={rc}\n")
    fh.write(f"{name}\n")
    fh.write(f"N {npts} R {RMIN!r} {rc!r}\n\n")
    for i in range(npts):
        fh.write(f"{i+1} {r[i]:.12g} {u[i]:.12g} {f[i]:.12g}\n")
    fh.write("\n")

    rr = np.linspace(RMIN * 1.05, rc * 0.999, 20000)
    h = 1e-6
    fnum = -(( -S*((sig/(rr+h))**4-(sig/rc)**4) ) - ( -S*((sig/(rr-h))**4-(sig/rc)**4) )) / (2*h)
    fana = -4.0 * S * sig ** 4 / rr ** 5
    rel = np.max(np.abs(fnum - fana) / np.maximum(np.abs(fana), 1e-12))
    return rel


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--npts", type=int, default=100000)
    ap.add_argument("--out", default="solvation.table")
    ap.add_argument("--S", type=float, default=M.S_SOLV,
                    help="solvation prefactor (default: the production S_SOLV)")
    a = ap.parse_args()
    M.S_SOLV = a.S

    with open(a.out, "w") as fh:
        fh.write("# Solvation potential  U = -S[(s/r)^4 - (s/rc)^4]\n")
        fh.write(f"# S = {M.S_SOLV} eps, rc = {M.RC_SOLV} sigma, generated by make_solv_table.py\n\n")
        e1 = section(fh, "CAT_MONO", M.sigma_ij(M.T_MONO, M.T_CAT), M.S_SOLV, M.RC_SOLV, a.npts)
        e2 = section(fh, "ANI_MONO", M.sigma_ij(M.T_MONO, M.T_ANI), M.S_SOLV, M.RC_SOLV, a.npts)


        e3 = section(fh, "SIG1_MONO", 1.0, M.S_SOLV, M.RC_SOLV, a.npts)

    dr = (M.RC_SOLV - RMIN) / (a.npts - 1)
    print(f"wrote {a.out}: 3 sections x {a.npts} points, dr = {dr:.3e} sigma")
    print(f"max |F_num - F_ana|/|F_ana| = {max(e1, e2, e3):.2e}")
    for t, nm in ((M.T_CAT, "cation"), (M.T_ANI, "anion")):
        s = M.sigma_ij(M.T_MONO, t)
        sig = M.solv_sigma(M.T_MONO, t)
        print(f"  {nm}-monomer: solvation s={sig:.2f}  U_solv(contact={s:.2f}) = "
              f"{-M.S_SOLV*((sig/s)**4-(sig/M.RC_SOLV)**4):+.4f} eps   "
              f"U_solv({M.RC_SOLV})=0")


if __name__ == "__main__":
    main()
