#!/usr/bin/env python3
"""Emit the LAMMPS force-field include file from tools/model.py.

Generated, never hand-edited, so the input scripts cannot drift from the
documented model.

Pair-style layout (hybrid/overlay):
  lj/cut           -> every pair involving a monomer (monomers carry q = 0, so
                      no Coulomb term is needed or missed for those pairs)
  lj/cut/coul/long -> ion-ion pairs (the only charged pairs)
  table            -> ion-monomer 1/r^4 solvation, on top of the WCA core
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import model as M

PAIRS = [(1, 1), (1, 2), (1, 3), (2, 2), (2, 3), (3, 3)]
SECTION = {M.T_CAT: "CAT_MONO", M.T_ANI: "ANI_MONO"}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--coul-cut", type=float, default=5.0)
    ap.add_argument("--table-npts", type=int, default=100000)
    ap.add_argument("--solv-sigma", choices=["ij", "one"], default=M.SOLV_SIGMA,
                    help="sigma in the solvation term: sigma_ij (eq. 3 as written) "
                         "or 1.0 (Hall's bornsolv convention; the production model)")
    ap.add_argument("--solv-ions", choices=["both", "cation"], default="both",
                    help="which ions feel the solvation term")
    ap.add_argument("--solv-style", choices=["table", "bornsolv"], default="table",
                    help="table: our tabulated 1/r^4; bornsolv: Hall's analytic pair "
                         "style (needs a LAMMPS build that includes pair_bornsolv)")
    ap.add_argument("--salt-free", action="store_true",
                    help="polymer only: no ions, no Coulomb, no solvation table")
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    if a.salt_free:
        return write_salt_free(a.out)

    L = []
    w = L.append
    w("# ---------------------------------------------------------------------")
    w("# Force field: Tsamopoulos & Wang, ACS Macro Lett. 13, 322 (2024)")
    w("# GENERATED by tools/write_ff.py -- do not edit by hand")
    w(f"#   q* = {M.QSTAR:.6f}, eps_r = {M.EPS_R}, l_B(T*=1) = {M.bjerrum_sigma(1.0):.4f} sigma")
    w("# ---------------------------------------------------------------------")
    w("variable tabfile index solvation.table")
    w("")
    w("bond_style      fene")
    w(f"bond_coeff      1 {M.FENE_K} {M.FENE_R0} {M.EPSILON} {M.SIGMA_T[M.T_MONO]}")
    w("special_bonds   fene")
    w("")
    solv_sub = (f"table linear {a.table_npts}" if a.solv_style == "table"
                else f"bornsolv {M.RC_SOLV}")
    w(f"pair_style      hybrid/overlay lj/cut {M.CUT_MM} "
      f"lj/cut/coul/long {M.CUT_MM} {a.coul_cut} {solv_sub}")
    w("")
    for (i, j) in PAIRS:
        sub = "lj/cut" if (i == M.T_MONO or j == M.T_MONO) else "lj/cut/coul/long"
        w(f"pair_coeff      {i} {j} {sub} {M.EPSILON} "
          f"{M.sigma_ij(i,j):.10g} {M.lj_cut(i,j):.10g}")
    w("")
    w("# SI eq. (1) is the energy-shifted form for EVERY pair, including the")
    w("# monomer-monomer pair cut at 2.0 sigma.  The shift changes no force and")
    w("# no virial, so densities and dynamics are unaffected either way.")
    w("pair_modify     shift yes")
    w("")
    w(f"# solvation variant: sigma={a.solv_sigma}  ions={a.solv_ions}")
    for (i, j) in PAIRS:
        if M.is_solvated(i, j):
            ion = j if i == M.T_MONO else i
            if a.solv_ions == "cation" and ion != M.T_CAT:
                continue
            sig = M.solv_sigma(i, j, a.solv_sigma)
            if a.solv_style == "bornsolv":
                # bornsolv: E = -eps [(sigma/r)^4 - (sigma/rc)^4]; eps > 0 attracts
                w(f"pair_coeff      {i} {j} bornsolv {M.S_SOLV} {sig:.10g} {M.RC_SOLV}")
            else:
                sec = SECTION[ion] if a.solv_sigma == "ij" else "SIG1_MONO"
                w(f"pair_coeff      {i} {j} table ${{tabfile}} {sec} {M.RC_SOLV}")
    w("")
    w(f"dielectric      {M.EPS_R}")
    w("variable        pppm_acc index 1.0e-4")
    w("kspace_style    pppm ${pppm_acc}")
    w("")
    w("# charges are carried in the data/restart file; reassert for safety")
    for t in (M.T_MONO, M.T_CAT, M.T_ANI):
        w(f"set             type {t} charge {M.CHARGE_T[t]:.6f}")
    w("")
    w("group           monomers type 1")
    w("group           cations  type 2")
    w("group           anions   type 3")
    w("group           ions     type 2 3")
    w("")
    w("neighbor        0.4 bin")
    w("neigh_modify    delay 0 every 1 check yes")
    w("")

    with open(a.out, "w") as f:
        f.write("\n".join(L))
    print(f"wrote {a.out}")
    print("\n".join(L))


def write_salt_free(out):
    """Polymer-only force field: the same monomer-monomer LJ and FENE as the
    full model, nothing else.  Used to separate the polymer contribution to
    the p=0 density from the ion-monomer (solvation) contribution."""
    L = [
        "# ---------------------------------------------------------------------",
        "# SALT-FREE reference force field -- polymer part of the model only",
        "# GENERATED by tools/write_ff.py --salt-free -- do not edit by hand",
        "# ---------------------------------------------------------------------",
        "variable tabfile index unused",
        "",
        "bond_style      fene",
        f"bond_coeff      1 {M.FENE_K} {M.FENE_R0} {M.EPSILON} {M.SIGMA_T[M.T_MONO]}",
        "special_bonds   fene",
        "",
        f"pair_style      lj/cut {M.CUT_MM}",
        f"pair_coeff      * * {M.EPSILON} {M.SIGMA_T[M.T_MONO]} {M.CUT_MM}",
        "pair_modify     shift yes         # SI eq. (1)",
        "",
        "group           monomers type 1",
        "group           cations  type 2",
        "group           anions   type 3",
        "group           ions     type 2 3",
        "",
        "neighbor        0.4 bin",
        "neigh_modify    delay 0 every 1 check yes",
        "",
    ]
    open(out, "w").write("\n".join(L))
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
